config/routes.rb
Rails.application.routes.draw do
  #get 'profiles/show'
  devise_for :users

  resources :restaurants do
    resources :dishes, only: [:create]
    resources :orders, only: [:index]
    get "/dashboard", to: "restaurants#dashboard"
    get "/index_today", to: "orders#index_today"
    get "/index_owner", to: "dishes#index_owner"
  end

  resources :dishes, only: [:index, :edit, :update, :destroy] do
    resources :orders, only: [:create, :index]


  end
  resources :profiles, only: [:show]
  resources :orders, only: [:show, :update]
  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end

  patch ":id/claim", to: "orders#claim", as: :claim
  root to: 'pages#home'
end

app/views/dashboard/show.html.erb
<div class="container-fluid mt-4">
  <div class="row justify-content-center">

    <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block sidebar collapse" style="width: 25%">
      <div class="position-sticky pt-3">
        <ul class="nav flex-column">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-home"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path><polyline points="9 22 9 12 15 12 15 22"></polyline></svg>
              Dashboard
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file"><path d="M13 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V9z"></path><polyline points="13 2 13 9 20 9"></polyline></svg>
              Pedidos
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-shopping-cart"><circle cx="9" cy="21" r="1"></circle><circle cx="20" cy="21" r="1"></circle><path d="M1 1h4l2.68 13.39a2 2 0 0 0 2 1.61h9.72a2 2 0 0 0 2-1.61L23 6H6"></path></svg>
              Calendário
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-users"><path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path><circle cx="9" cy="7" r="4"></circle><path d="M23 21v-2a4 4 0 0 0-3-3.87"></path><path d="M16 3.13a4 4 0 0 1 0 7.75"></path></svg>
              Minha Loja
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              Log out
            </a>
          </li>
        </ul>
      </div>
    </nav>

    <div class="col-12 col-lg-6">
      <main class="card-space col-md-9 col-lg-10 px-md-4 mb-15">
        <div class="card-model p-3 card-border">
            <h1>Seja Bem-vindo!</h1>
            <p> Nesta página você encontra tudo sobre os seus dados cadastrados, seus pratos disponíveis, pedidos e pagamentos.</p>
             <p> Obrigado por fazer parte desta revolução :) </p>
        </div>
        <div class="card">
          <div class="d-flex justify-content-between">
            <div class="card m-5 p-3 card-main card-border col-12 col-lg-5">
              <h1>Adicione a refeição que sobrou aqui:</h1>
              <p>Conte-nos um pouco sobre a comida que você oferecerá em suas bolsas mágicas e prepare-se para começar a economizar seu excedente de comida.</p>
              <%= link_to "Adicione o prato", new_restaurant_dish_path(current_user), class:"btn btn-primeiro"%>
            </div>

            <div class="card m-5 p-3 card-main card-border col-12 col-lg-5">
              <h1>Acompanhe os seus pedidos:</h1>
              <p> Aqui você pode acompanhar quais pedidos você têm em andamento, qual é o horário de coleta, forma de pagamento e o nome do cliente que irá recolher.</p>
              <%= link_to "Seus pedidos", dish_orders_path(current_user), class:"btn btn-primeiro"%>
            </div>
          </div>
        </div>
      </main>
    </div>
  </div>
</div>